name: CLI CI

on:
  push:
    branches:
    - dev

jobs:
  test:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Compile
      run: bin/qmk compile -kb redox -km prewk